package com.exam.controller;

import com.exam.dto.AutoGenerateDTO;
import com.exam.dto.ExamStatistics;
import com.exam.entity.Exam;
import com.exam.entity.ExamQuestion;
import com.exam.entity.Question;
import com.exam.entity.User;
import com.exam.repository.UserRepository;
import com.exam.service.ExamService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.security.Principal;
import java.util.List;
import java.util.Map;

@Tag(name = "考试管理", description = "考试 CRUD、题目组卷、发布、统计分析等接口")
@RestController
@RequestMapping("/api/exams")
public class ExamController {

    private final ExamService examService;
    private final UserRepository userRepository;

    public ExamController(ExamService examService, UserRepository userRepository) {
        this.examService = examService;
        this.userRepository = userRepository;
    }

    @Operation(summary = "获取考试列表", description = "根据当前用户角色返回可见的考试列表：学生只看到已发布且自己可见的考试，教师/管理员看到全部")
    @ApiResponses(value = {
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "成功返回考试列表",
                    content = @Content(mediaType = "application/json")),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "权限不足")
    })
    @GetMapping
    public List<Exam> getExams(Principal principal) {
        User user = userRepository.findByUsername(principal.getName()).orElse(null);
        if (user != null && "STUDENT".equals(user.getRole())) {
            return examService.getExamsForStudent(principal.getName());
        }
        return examService.getAllExams();
    }

    @Operation(summary = "获取考试详情", description = "根据 ID 查询单个考试的完整信息")
    @ApiResponses(value = {
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "成功返回考试详情"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "考试不存在")
    })
    @GetMapping("/{id}")
    public Exam getExam(
            @Parameter(description = "考试 ID", required = true, example = "1")
            @PathVariable Long id) {
        return examService.getExamById(id);
    }

    @Operation(summary = "创建考试", description = "创建一个新的考试（草稿状态）。仅 TEACHER 和 ADMIN 角色可调用")
    @ApiResponses(value = {
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "创建成功"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "参数校验失败"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "未登录"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "403", description = "需要 TEACHER 或 ADMIN 角色")
    })
    @PostMapping
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public Exam createExam(@RequestBody Exam exam, Principal principal) {
        return examService.createExam(exam, principal.getName());
    }

    @Operation(summary = "创建题目", description = "向题库新增一道题目。仅 TEACHER 和 ADMIN 角色可调用")
    @PostMapping("/questions")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public Question createQuestion(@RequestBody Question question, Principal principal) {
        return examService.createQuestion(question, principal.getName());
    }

    @Operation(summary = "添加题目到考试", description = "将已有题库中的题目关联到指定考试，可设置分值和显示顺序")
    @PostMapping("/{examId}/questions")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> addQuestionToExam(
            @Parameter(description = "考试 ID", required = true) @PathVariable Long examId,
            @RequestBody Map<String, Object> body) {
        Long questionId = Long.valueOf(body.get("questionId").toString());
        Integer score = body.containsKey("score") ? Integer.valueOf(body.get("score").toString()) : null;
        Integer sequence = body.containsKey("sequence") ? Integer.valueOf(body.get("sequence").toString()) : 0;

        examService.addQuestionToExam(examId, questionId, score, sequence);
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "获取考试题目列表", description = "返回指定考试的全部题目，根据考试配置可能进行题目乱序和选项乱序")
    @GetMapping("/{examId}/questions")
    public List<ExamQuestion> getExamQuestions(@PathVariable Long examId) {
        return examService.getExamQuestions(examId);
    }

    @PutMapping("/{examId}/questions/{questionId}")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> updateExamQuestion(@PathVariable Long examId, @PathVariable Long questionId, @RequestBody Map<String, Object> body) {
        Integer score = body.containsKey("score") ? Integer.valueOf(body.get("score").toString()) : null;
        Integer sequence = body.containsKey("sequence") ? Integer.valueOf(body.get("sequence").toString()) : null;
        examService.updateExamQuestion(examId, questionId, score, sequence);
        return ResponseEntity.ok().build();
    }

    @DeleteMapping("/{examId}/questions/{questionId}")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> removeQuestionFromExam(@PathVariable Long examId, @PathVariable Long questionId) {
        examService.removeQuestionFromExam(examId, questionId);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/questions")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public List<Question> getAllQuestions() {
        return examService.getAllQuestions();
    }

    @Operation(summary = "发布考试", description = "更新考试信息并将考试状态由草稿改为已发布，同时向目标学生推送通知")
    @PostMapping("/{examId}/publish")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> publishExam(@PathVariable Long examId, @RequestBody Exam details) {
        examService.publishExam(examId, details);
        return ResponseEntity.ok().build();
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> deleteExam(@PathVariable Long id) {
        examService.deleteExam(id);
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "获取考试统计", description = "返回考试的各项统计数据：平均分、最高分、最低分、及格率、分数分布、排名、题目分析")
    @GetMapping("/{id}/statistics")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<ExamStatistics> getExamStatistics(@PathVariable Long id) {
        return ResponseEntity.ok(examService.getExamStatistics(id));
    }

    @Operation(summary = "自动组卷", description = "根据题型数量、难度、知识点等策略自动从题库选题并组卷")
    @PostMapping("/{examId}/auto-generate")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> autoGenerateExam(@PathVariable Long examId, @RequestBody AutoGenerateDTO strategy) {
        examService.autoGenerateExam(examId, strategy);
        return ResponseEntity.ok().build();
    }

    @Operation(summary = "导出考试统计 CSV", description = "导出指定考试的统计数据为 CSV 文件，包含整体数据、排名、题目分析")
    @GetMapping("/{id}/export")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<byte[]> exportExamStatistics(@PathVariable Long id) {
        byte[] data = examService.exportExamStatistics(id);
        return ResponseEntity.ok()
                .header(org.springframework.http.HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=exam_stats_" + id + ".csv")
                .header(org.springframework.http.HttpHeaders.CONTENT_TYPE, "text/csv; charset=UTF-8")
                .body(data);
    }

    @Operation(summary = "记录作弊事件", description = "学生端上报切屏等疑似作弊行为，服务端记录日志并计数")
    @PostMapping("/{examId}/record-cheating")
    public ResponseEntity<?> recordCheating(@PathVariable Long examId, @RequestBody Map<String, String> body, Principal principal) {
        String type = body.get("type");
        String detail = body.get("detail");
        examService.recordCheatingEvent(examId, principal.getName(), type, detail);
        return ResponseEntity.ok().build();
    }
}
