package com.exam.controller;

import com.exam.entity.Exam;
import com.exam.entity.ExamQuestion;
import com.exam.entity.Question;
import com.exam.entity.User;
import com.exam.repository.UserRepository;
import com.exam.service.ExamService;
import com.exam.dto.AutoGenerateDTO;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.security.Principal;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/exams")
public class ExamController {
    
    private final ExamService examService;
    private final UserRepository userRepository;

    public ExamController(ExamService examService, UserRepository userRepository) {
        this.examService = examService;
        this.userRepository = userRepository;
    }

    @GetMapping
    public List<Exam> getExams(Principal principal) {
        User user = userRepository.findByUsername(principal.getName()).orElse(null);
        if (user != null && "STUDENT".equals(user.getRole())) {
            return examService.getExamsForStudent(principal.getName());
        }
        return examService.getAllExams();
    }

    @GetMapping("/{id}")
    public Exam getExam(@PathVariable Long id) {
        return examService.getExamById(id);
    }

    @PostMapping
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public Exam createExam(@RequestBody Exam exam, Principal principal) {
        return examService.createExam(exam, principal.getName());
    }

    @PostMapping("/questions")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public Question createQuestion(@RequestBody Question question, Principal principal) {
        return examService.createQuestion(question, principal.getName());
    }

    @PostMapping("/{examId}/questions")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> addQuestionToExam(@PathVariable Long examId, @RequestBody Map<String, Object> body) {
        Long questionId = Long.valueOf(body.get("questionId").toString());
        Integer score = body.containsKey("score") ? Integer.valueOf(body.get("score").toString()) : null;
        Integer sequence = body.containsKey("sequence") ? Integer.valueOf(body.get("sequence").toString()) : 0;
        
        examService.addQuestionToExam(examId, questionId, score, sequence);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/{examId}/questions")
    public List<ExamQuestion> getExamQuestions(@PathVariable Long examId) {
        return examService.getExamQuestions(examId);
    }

    @PutMapping("/{examId}/questions/{questionId}")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> updateExamQuestion(@PathVariable Long examId, @PathVariable Long questionId, @RequestBody Map<String, Object> body) {
        Integer score = body.containsKey("score") ? Integer.valueOf(body.get("score").toString()) : null;
        Integer sequence = body.containsKey("sequence") ? Integer.valueOf(body.get("sequence").toString()) : null;
        examService.updateExamQuestion(examId, questionId, score, sequence);
        return ResponseEntity.ok().build();
    }

    @DeleteMapping("/{examId}/questions/{questionId}")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> removeQuestionFromExam(@PathVariable Long examId, @PathVariable Long questionId) {
        examService.removeQuestionFromExam(examId, questionId);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/questions")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public List<Question> getAllQuestions() {
        return examService.getAllQuestions();
    }

    @PostMapping("/{examId}/publish")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> publishExam(@PathVariable Long examId, @RequestBody Exam details) {
        examService.publishExam(examId, details);
        return ResponseEntity.ok().build();
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> deleteExam(@PathVariable Long id) {
        examService.deleteExam(id);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/{id}/statistics")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<com.exam.dto.ExamStatistics> getExamStatistics(@PathVariable Long id) {
        return ResponseEntity.ok(examService.getExamStatistics(id));
    }

    @PostMapping("/{examId}/auto-generate")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<?> autoGenerateExam(@PathVariable Long examId, @RequestBody AutoGenerateDTO strategy) {
        examService.autoGenerateExam(examId, strategy);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/{id}/export")
    @PreAuthorize("hasRole('TEACHER') or hasRole('ADMIN')")
    public ResponseEntity<byte[]> exportExamStatistics(@PathVariable Long id) {
        byte[] data = examService.exportExamStatistics(id);
        return ResponseEntity.ok()
                .header(org.springframework.http.HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=exam_stats_" + id + ".csv")
                .header(org.springframework.http.HttpHeaders.CONTENT_TYPE, "text/csv; charset=UTF-8")
                .body(data);
    }

    @PostMapping("/{examId}/record-cheating")
    public ResponseEntity<?> recordCheating(@PathVariable Long examId, @RequestBody Map<String, String> body, Principal principal) {
        String type = body.get("type");
        String detail = body.get("detail");
        examService.recordCheatingEvent(examId, principal.getName(), type, detail);
        return ResponseEntity.ok().build();
    }
}
