package com.exam.dto;

import lombok.Data;
import java.util.List;
import java.util.Map;

@Data
public class AutoGenerateDTO {
    private String subject;
    private List<String> knowledgePoints;
    private List<Integer> difficultyLevels;
    
    // Key: Question Type (SINGLE, MULTI, etc.), Value: Number of questions
    private Map<String, Integer> countsByType;
    
    // Key: Question Type, Value: Score per question
    private Map<String, Integer> scoresByType;
    
    private Integer totalScore;
}
