package com.exam.service;

import com.exam.common.BusinessException;
import com.exam.common.ErrorCode;
import com.exam.entity.Exam;
import com.exam.entity.ExamQuestion;
import com.exam.entity.Question;
import com.exam.entity.Submission;
import com.exam.entity.SubmissionAnswer;
import com.exam.entity.User;
import com.exam.repository.ExamQuestionRepository;
import com.exam.repository.ExamRepository;
import com.exam.repository.QuestionRepository;
import com.exam.repository.UserRepository;
import com.exam.dto.AutoGenerateDTO;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;
import java.util.Collections;
import java.util.Random;
import java.util.stream.Collectors;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;

@Service
public class ExamService {
    private final ExamRepository examRepository;
    private final QuestionRepository questionRepository;
    private final ExamQuestionRepository examQuestionRepository;
    private final UserRepository userRepository;
    private final com.exam.repository.SubmissionRepository submissionRepository;
    private final com.exam.repository.SubmissionAnswerRepository submissionAnswerRepository;
    private final NotificationService notificationService;

    public ExamService(ExamRepository examRepository, QuestionRepository questionRepository, ExamQuestionRepository examQuestionRepository, UserRepository userRepository, com.exam.repository.SubmissionRepository submissionRepository, com.exam.repository.SubmissionAnswerRepository submissionAnswerRepository, NotificationService notificationService) {
        this.examRepository = examRepository;
        this.questionRepository = questionRepository;
        this.examQuestionRepository = examQuestionRepository;
        this.userRepository = userRepository;
        this.submissionRepository = submissionRepository;
        this.submissionAnswerRepository = submissionAnswerRepository;
        this.notificationService = notificationService;
    }

    public List<Exam> getAllExams() {
        return examRepository.findAll();
    }

    public List<Exam> getExamsForStudent(String username) {
        return examRepository.findVisibleExams("PUBLISHED", username);
    }

    public Exam getExamById(Long id) {
        return examRepository.findById(id).orElseThrow(() -> new BusinessException(ErrorCode.EXAM_NOT_FOUND));
    }

    public Exam createExam(Exam exam, String username) {
        User user = userRepository.findByUsername(username).orElseThrow();
        exam.setCreator(user);
        exam.setState("DRAFT");
        return examRepository.save(exam);
    }
    
    public Question createQuestion(Question question, String username) {
        User user = userRepository.findByUsername(username).orElseThrow(() -> new BusinessException(ErrorCode.USER_NOT_FOUND));
        question.setCreator(user);
        return questionRepository.save(question);
    }

    @Transactional
    public void addQuestionToExam(Long examId, Long questionId, Integer score, Integer sequence) {
        Exam exam = getExamById(examId);
        Question question = questionRepository.findById(questionId).orElseThrow(() -> new BusinessException(ErrorCode.QUESTION_NOT_FOUND));
        
        ExamQuestion eq = new ExamQuestion();
        eq.setExam(exam);
        eq.setQuestion(question);
        eq.setScore(score != null ? score : question.getDefaultScore());
        eq.setSequence(sequence);
        
        examQuestionRepository.save(eq);
    }

    @Transactional
    public void updateExamQuestion(Long examId, Long questionId, Integer score, Integer sequence) {
        ExamQuestion eq = examQuestionRepository.findByExamIdOrderBySequenceAsc(examId).stream()
                .filter(item -> item.getQuestion().getId().equals(questionId))
                .findFirst()
                .orElseThrow(() -> new BusinessException(ErrorCode.QUESTION_NOT_FOUND, "题目不在该考试中"));
        
        if (score != null) eq.setScore(score);
        if (sequence != null) eq.setSequence(sequence);
        examQuestionRepository.save(eq);
    }

    @Transactional
    public void removeQuestionFromExam(Long examId, Long questionId) {
        ExamQuestion eq = examQuestionRepository.findByExamIdOrderBySequenceAsc(examId).stream()
                .filter(item -> item.getQuestion().getId().equals(questionId))
                .findFirst()
                .orElseThrow(() -> new BusinessException(ErrorCode.QUESTION_NOT_FOUND, "题目不在该考试中"));
        examQuestionRepository.delete(eq);
    }

    public List<ExamQuestion> getExamQuestions(Long examId) {
        Exam exam = examRepository.findById(examId).orElse(null);
        List<ExamQuestion> questions = examQuestionRepository.findByExamIdOrderBySequenceAsc(examId);
        
        if (exam == null) return questions;

        // Shuffle logic
        String currentUsername = org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication().getName();
        long seed = (long) currentUsername.hashCode() + examId;
        java.util.Random random = new java.util.Random(seed);

        if (Boolean.TRUE.equals(exam.getShuffleQuestions())) {
            java.util.Collections.shuffle(questions, random);
        }

        if (Boolean.TRUE.equals(exam.getShuffleOptions())) {
            com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
            for (ExamQuestion eq : questions) {
                Question q = eq.getQuestion();
                if (q.getOptions() != null && !q.getOptions().isEmpty()) {
                    try {
                        List<Map<String, Object>> options = mapper.readValue(q.getOptions(), new com.fasterxml.jackson.core.type.TypeReference<List<Map<String, Object>>>() {});
                        java.util.Collections.shuffle(options, random);
                        q.setOptions(mapper.writeValueAsString(options));
                    } catch (Exception e) {
                        // Log error or ignore
                    }
                }
            }
        }
        
        return questions;
    }

    public List<Question> getAllQuestions() {
        return questionRepository.findAll();
    }

    public void publishExam(Long examId, Exam details) {
        Exam exam = examRepository.findById(examId).orElseThrow(() -> new BusinessException(ErrorCode.EXAM_NOT_FOUND));
        
        // Update metadata
        if (details.getTitle() != null) exam.setTitle(details.getTitle());
        if (details.getDescription() != null) exam.setDescription(details.getDescription());
        if (details.getCourse() != null) exam.setCourse(details.getCourse());
        if (details.getDuration() != null) exam.setDuration(details.getDuration());
        if (details.getStartTime() != null) exam.setStartTime(details.getStartTime());
        if (details.getEndTime() != null) exam.setEndTime(details.getEndTime());
        
        // Update Security
        if (details.getAllowTabSwitch() != null) exam.setAllowTabSwitch(details.getAllowTabSwitch());
        if (details.getTabSwitchLimit() != null) exam.setTabSwitchLimit(details.getTabSwitchLimit());
        if (details.getEnableCamera() != null) exam.setEnableCamera(details.getEnableCamera());
        if (details.getShuffleQuestions() != null) exam.setShuffleQuestions(details.getShuffleQuestions());
        if (details.getShuffleOptions() != null) exam.setShuffleOptions(details.getShuffleOptions());
        
        // Update Results
        if (details.getPublicScores() != null) exam.setPublicScores(details.getPublicScores());
        if (details.getAllowViewAnalysis() != null) exam.setAllowViewAnalysis(details.getAllowViewAnalysis());
        
        // Update Targeting
        if (details.getTargetAudience() != null) exam.setTargetAudience(details.getTargetAudience());
        if (details.getTargetIds() != null) exam.setTargetIds(details.getTargetIds());

        exam.setState("PUBLISHED");
        examRepository.save(exam);

        // CREATE NOTIFICATIONS
        if ("ALL".equals(exam.getTargetAudience())) {
            List<User> students = userRepository.findAll().stream()
                    .filter(u -> "STUDENT".equals(u.getRole()))
                    .collect(java.util.stream.Collectors.toList());
            for (User s : students) {
                notificationService.createNotification(s, "新考试发布", "您有一场新考试: " + exam.getTitle(), "EXAM_PUBLISHED", exam.getId());
            }
        } else if (exam.getTargetIds() != null) {
            String[] ids = exam.getTargetIds().split(",");
            for (String id : ids) {
                String trimmedId = id.trim();
                userRepository.findByUsername(trimmedId).ifPresent(s -> {
                    notificationService.createNotification(s, "新考试发布", "您有一场新考试: " + exam.getTitle(), "EXAM_PUBLISHED", exam.getId());
                });
                try {
                    Long numericId = Long.parseLong(trimmedId);
                    userRepository.findById(numericId).ifPresent(s -> {
                        notificationService.createNotification(s, "新考试发布", "您有一场新考试: " + exam.getTitle(), "EXAM_PUBLISHED", exam.getId());
                    });
                } catch (NumberFormatException ignored) {}
            }
        }
    }

    @Transactional
    public void deleteExam(Long examId) {
        Exam exam = examRepository.findById(examId).orElseThrow(() -> new BusinessException(ErrorCode.EXAM_NOT_FOUND));
        
        // 1. Delete all exam questions
        List<ExamQuestion> eqs = examQuestionRepository.findByExamIdOrderBySequenceAsc(examId);
        examQuestionRepository.deleteAll(eqs);
        
        // 2. Delete all submissions (cascades to answers)
        List<Submission> submissions = submissionRepository.findByExamId(examId);
        submissionRepository.deleteAll(submissions);
        
        // 3. Delete exam
        examRepository.delete(exam);
    }

    public com.exam.dto.ExamStatistics getExamStatistics(Long examId) {
        Exam exam = getExamById(examId);
        List<Submission> submissions = submissionRepository.findByExamId(examId);
        List<ExamQuestion> examQuestions = examQuestionRepository.findByExamIdOrderBySequenceAsc(examId);
        
        com.exam.dto.ExamStatistics stats = new com.exam.dto.ExamStatistics();
        stats.setExamId(exam.getId());
        stats.setTitle(exam.getTitle());
        stats.setTotalSubmissions(submissions.size());
        
        // Calculate Total Participants
        int totalParticipants = 0;
        if ("ALL".equals(exam.getTargetAudience())) {
            totalParticipants = (int) userRepository.countByRole("STUDENT");
        } else if (exam.getTargetIds() != null) {
            totalParticipants = exam.getTargetIds().split(",").length;
        }
        stats.setTotalParticipants(totalParticipants);
        stats.setAbsentCount(Math.max(0, totalParticipants - submissions.size()));

        if (submissions.isEmpty()) {
            return stats;
        }
        
        int totalScore = 0;
        int max = Integer.MIN_VALUE;
        int min = Integer.MAX_VALUE;
        int passCount = 0;
        java.util.Map<String, Integer> dist = new java.util.HashMap<>();
        dist.put("0-59", 0);
        dist.put("60-69", 0);
        dist.put("70-79", 0);
        dist.put("80-89", 0);
        dist.put("90-100", 0);
        
        int totalPossibleScore = examQuestions.stream().mapToInt(ExamQuestion::getScore).sum();
        int passScore = (int) (totalPossibleScore * 0.6);
        
        // Rankings
        List<com.exam.dto.ExamStatistics.StudentRanking> rankings = new java.util.ArrayList<>();
        
        for (Submission s : submissions) {
            int score = s.getScore() != null ? s.getScore() : 0;
            totalScore += score;
            if (score > max) max = score;
            if (score < min) min = score;
            if (score >= passScore) passCount++;
            
            if (score < 60) dist.put("0-59", dist.get("0-59") + 1);
            else if (score < 70) dist.put("60-69", dist.get("60-69") + 1);
            else if (score < 80) dist.put("70-79", dist.get("70-79") + 1);
            else if (score < 90) dist.put("80-89", dist.get("80-89") + 1);
            else dist.put("90-100", dist.get("90-100") + 1);
            
            com.exam.dto.ExamStatistics.StudentRanking r = new com.exam.dto.ExamStatistics.StudentRanking();
            r.setUsername(s.getStudent().getUsername());
            r.setFullName(s.getStudent().getFullName());
            r.setScore(score);
            r.setSubmissionId(s.getId());
            rankings.add(r);
        }
        
        // Sort rankings
        rankings.sort((a, b) -> b.getScore().compareTo(a.getScore()));
        for (int i = 0; i < rankings.size(); i++) {
            rankings.get(i).setRank(i + 1);
        }
        stats.setRankings(rankings);

        // Question Analysis
        List<com.exam.dto.ExamStatistics.QuestionStat> qStats = new java.util.ArrayList<>();
        List<Object[]> analysisResults = submissionAnswerRepository.getQuestionAnalysis(examId);
        java.util.Map<Long, Object[]> analysisMap = analysisResults.stream()
                .collect(java.util.stream.Collectors.toMap(
                        res -> (Long) res[0],
                        res -> res
                ));

        for (ExamQuestion eq : examQuestions) {
            Question q = eq.getQuestion();
            com.exam.dto.ExamStatistics.QuestionStat qs = new com.exam.dto.ExamStatistics.QuestionStat();
            qs.setQuestionId(q.getId());
            qs.setContent(q.getContent());
            qs.setType(q.getType());
            qs.setSequence(eq.getSequence());
            
            Object[] analysis = analysisMap.get(q.getId());
            if (analysis != null) {
                qs.setAverageScore((Double) analysis[1]);
                qs.setCorrectRate((Double) analysis[2]);
            } else {
                qs.setAverageScore(0.0);
                qs.setCorrectRate(0.0);
            }
            qStats.add(qs);
        }
        stats.setQuestionAnalysis(qStats);

        stats.setAverageScore((double) totalScore / submissions.size());
        stats.setMaxScore(max);
        stats.setMinScore(min);
        stats.setPassRate((double) passCount / submissions.size() * 100);
        stats.setScoreDistribution(dist);
        
        return stats;
    }

    @Transactional
    public void autoGenerateExam(Long examId, AutoGenerateDTO strategy) {
        Exam exam = getExamById(examId);
        
        // Clear existing questions if any (optional, based on requirement "generate after preview and adjust")
        // But for "auto generate" usually we start fresh or append. Let's start fresh.
        List<ExamQuestion> existing = examQuestionRepository.findByExamIdOrderBySequenceAsc(examId);
        examQuestionRepository.deleteAll(existing);

        int currentSequence = 1;
        
        for (java.util.Map.Entry<String, Integer> entry : strategy.getCountsByType().entrySet()) {
            String type = entry.getKey();
            int count = entry.getValue();
            
            List<Question> pool = questionRepository.findBySubjectAndType(strategy.getSubject(), type);
            
            // Filter by difficulty and knowledge points in memory for simplicity
            if (strategy.getDifficultyLevels() != null && !strategy.getDifficultyLevels().isEmpty()) {
                pool = pool.stream().filter(q -> strategy.getDifficultyLevels().contains(q.getDifficulty())).collect(java.util.stream.Collectors.toList());
            }
            if (strategy.getKnowledgePoints() != null && !strategy.getKnowledgePoints().isEmpty()) {
                pool = pool.stream().filter(q -> strategy.getKnowledgePoints().contains(q.getKnowledgePoint())).collect(java.util.stream.Collectors.toList());
            }

            java.util.Collections.shuffle(pool);
            List<Question> selected = pool.subList(0, Math.min(count, pool.size()));
            
            for (Question q : selected) {
                ExamQuestion eq = new ExamQuestion();
                eq.setExam(exam);
                eq.setQuestion(q);
                
                Integer score = null;
                if (strategy.getScoresByType() != null) {
                    score = strategy.getScoresByType().get(type);
                }
                eq.setScore(score != null ? score : q.getDefaultScore());
                
                eq.setSequence(currentSequence++);
                examQuestionRepository.save(eq);
            }
        }
    }

    public byte[] exportExamStatistics(Long examId) {
        com.exam.dto.ExamStatistics stats = getExamStatistics(examId);
        StringBuilder sb = new StringBuilder();
        // Add BOM for Excel
        sb.append("\uFEFF");
        
        // 1. Overall
        sb.append("考试名称,").append(stats.getTitle()).append("\n");
        sb.append("应考人数,").append(stats.getTotalParticipants()).append("\n");
        sb.append("实考人数,").append(stats.getTotalSubmissions()).append("\n");
        sb.append("缺考人数,").append(stats.getAbsentCount()).append("\n");
        sb.append("平均分,").append(String.format("%.2f", stats.getAverageScore())).append("\n");
        sb.append("最高分,").append(stats.getMaxScore()).append("\n");
        sb.append("最低分,").append(stats.getMinScore()).append("\n");
        sb.append("及格率,").append(String.format("%.2f%%", stats.getPassRate())).append("\n\n");
        
        // 2. Rankings
        sb.append("成绩排名\n");
        sb.append("排名,学号,姓名,得分\n");
        for (com.exam.dto.ExamStatistics.StudentRanking r : stats.getRankings()) {
            sb.append(r.getRank()).append(",")
              .append(r.getUsername()).append(",")
              .append(r.getFullName()).append(",")
              .append(r.getScore()).append("\n");
        }
        sb.append("\n");
        
        // 3. Question Analysis
        sb.append("题目分析\n");
        sb.append("题号,题型,平均分,正确率,内容\n");
        for (com.exam.dto.ExamStatistics.QuestionStat qs : stats.getQuestionAnalysis()) {
            sb.append(qs.getSequence()).append(",")
              .append(qs.getType()).append(",")
              .append(String.format("%.2f", qs.getAverageScore())).append(",")
              .append(String.format("%.2f%%", qs.getCorrectRate())).append(",")
              .append(qs.getContent().replace(",", " ").replace("\n", " ")).append("\n");
        }
        
        return sb.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
    }

    @Transactional
    public void recordCheatingEvent(Long examId, String username, String type, String detail) {
        Submission submission = (submissionRepository.findByExamIdAndStudentUsername(examId, username))
                .stream().filter(s -> "IN_PROGRESS".equals(s.getState())).findFirst()
                .orElse(null);
        
        if (submission == null) return;

        if ("TAB_SWITCH".equals(type)) {
            submission.setTabSwitchCount(submission.getTabSwitchCount() + 1);
        }

        String logEntry = String.format("[%s] %s: %s", java.time.LocalDateTime.now(), type, detail);
        if (submission.getCheatingLogs() == null) {
            submission.setCheatingLogs(logEntry);
        } else {
            submission.setCheatingLogs(submission.getCheatingLogs() + "\n" + logEntry);
        }
        
        submissionRepository.save(submission);
    }
}
